export const GRAMMAR_ROLE_MEANINGS: Record<string, string> = {
  '谓语': '句子核心动作或状态。\n例: The report *summarizes* Q1 results.',
  '主语': '动作或状态的发出者。\n例: *The team* delivered the feature.',
  '被动主语': '被动动作的承受者。\n例: *The budget* was approved.',
  '从句主语': '从句里的主语。\n例: I know [*she* will join].',
  '从句被动主语': '从句里被动承受者。\n例: I heard [*the proposal* was rejected].',
  '宾语': '动作作用的对象。\n例: We updated *the roadmap*.',
  '间接宾语': '动作的接收/受益对象。\n例: She sent *me* the file.',
  '介词宾语': '介词后面的对象。\n例: in *the meeting*.',
  '系表': '系动词后的补足成分。\n例: The plan is *clear*.',
  '系动词': '连接主语和表语。\n例: The goal *is* achievable.',
  '助动词': '辅助表达时态/语态/否定。\n例: We *have* finished.',
  '被动助动词': '被动语态的辅助词。\n例: The task *was* assigned.',
  '否定': '否定语义标记。\n例: We do *not* agree.',
  '副词修饰': '修饰动词/形容词/句子。\n例: The system runs *smoothly*.',
  '形容修饰': '修饰名词。\n例: *urgent* request.',
  '限定词': '限定名词范围。\n例: *this* document.',
  '介词标记': '引出介词短语。\n例: *in* the report.',
  '从属标记': '连接主从句。\n例: *because* it failed.',
  '介词': '引出介词结构。\n例: *with* a deadline.',
  '复合词': '多个词组合成整体。\n例: *project* plan.',
  '并列': '并列成分。\n例: budget *and* timeline.',
  '并列连接': '连接并列成分。\n例: sales *and* marketing.',
  '同位语': '对名词进一步说明。\n例: Our manager, *Lily*.',
  '名词修饰': '名词修饰名词。\n例: *client* feedback.',
  '数词修饰': '数量修饰。\n例: *three* tasks.',
  '所有格': '所属关系。\n例: *John\'s* report.',
  '定语从句': '修饰名词的从句。\n例: the plan *that we approved*.',
  '状语从句': '说明时间/条件/原因。\n例: *When we finish*, we deploy.',
  '补语从句': '补足谓语信息。\n例: I think *that it works*.',
  '开放补语': '不带 that 的补语结构。\n例: I want *to ship*.',
  '并列分句': '并列的两个句子。\n例: We shipped, *and* users adopted.',
  '被动语态': '用 be + 过去分词，强调承受者。\n例: The task *was assigned* yesterday.',
  '介词短语': '介词 + 名词/代词构成的短语。\n例: *in the report*.',
  '语法': '语法功能提示。\n例: 结构性词。',
  '词汇': '词汇性成分。\n例: 实义词。',
};
